#!/usr/bin/env python3
"""Merge themed vocabulary chunks into the single dataset the app loads.

Reads every data/chunks/chunk*.json, validates the schema, de-duplicates by
(normalised headword + part of speech), sorts by level then alphabetically, and
writes:
  - data/words.js   -> sets window.LUXFLASH_WORDS (works from file:// and Pages)
  - data/words.json -> same data, handy for reuse / inspection

Run:  python3 scripts/build_data.py
"""
import json
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHUNK_GLOB = os.path.join(ROOT, "data", "chunks", "chunk*.json")

LEVELS = {"A1": 0, "A2": 1, "B1": 2, "B2": 3}
POS = {"noun", "verb", "adjective", "adverb", "pronoun", "preposition",
       "conjunction", "numeral", "phrase", "interjection", "determiner", "number"}
REQUIRED = ["lb", "en", "pos", "level"]

ACCENT = str.maketrans("äàâëéèêïîöôüûç", "aaaeeeeiioouuc")


def norm(s):
    return re.sub(r"[^a-z0-9]+", "", str(s).lower().translate(ACCENT))


def clean(entry):
    """Return a normalised entry dict, or None if unusable."""
    if not isinstance(entry, dict):
        return None
    for k in REQUIRED:
        if not entry.get(k):
            return None
    lb = str(entry["lb"]).strip()
    pos = str(entry.get("pos", "")).strip().lower()
    if pos == "number":
        pos = "numeral"
    if pos == "article":
        pos = "determiner"
    if pos not in POS:
        pos = "phrase"
    level = str(entry.get("level", "")).strip().upper()
    if level not in LEVELS:
        level = "A2"
    gender = str(entry.get("gender", "")).strip().lower()
    if gender not in ("m", "f", "n"):
        gender = ""
    out = {
        "lb": lb,
        "en": str(entry.get("en", "")).strip(),
        "de": str(entry.get("de", "")).strip(),
        "fr": str(entry.get("fr", "")).strip(),
        "pos": pos,
        "gender": gender,
        "level": level,
        "category": str(entry.get("category", "")).strip().lower(),
        "ex_lb": str(entry.get("ex_lb", "")).strip(),
        "ex_en": str(entry.get("ex_en", "")).strip(),
    }
    if entry.get("plural"):
        out["plural"] = str(entry["plural"]).strip()
    # optional LOD entry id -> enables native audio (see scripts/fetch_lod_audio.py)
    if entry.get("lodId"):
        out["lodId"] = str(entry["lodId"]).strip()
    return out


def main():
    files = sorted(glob.glob(CHUNK_GLOB))
    if not files:
        print("No chunk files found at", CHUNK_GLOB, file=sys.stderr)
        sys.exit(1)

    seen = {}
    stats = {}
    dropped = 0
    for f in files:
        try:
            data = json.load(open(f, encoding="utf-8"))
        except Exception as e:  # noqa
            print(f"  ! skipping {os.path.basename(f)}: {e}", file=sys.stderr)
            continue
        n_ok = 0
        for raw in data:
            e = clean(raw)
            if not e:
                dropped += 1
                continue
            key = (norm(e["lb"]), e["pos"])
            if key in seen:
                dropped += 1
                continue
            seen[key] = e
            n_ok += 1
        stats[os.path.basename(f)] = n_ok

    words = list(seen.values())
    words.sort(key=lambda w: (LEVELS.get(w["level"], 9), w["lb"].lower()))

    out_js = os.path.join(ROOT, "data", "words.js")
    out_json = os.path.join(ROOT, "data", "words.json")
    payload = json.dumps(words, ensure_ascii=False, separators=(",", ":"))
    with open(out_js, "w", encoding="utf-8") as fh:
        fh.write("/* Auto-generated by scripts/build_data.py — do not edit by hand. */\n")
        fh.write("window.LUXFLASH_WORDS = " + payload + ";\n")
    with open(out_json, "w", encoding="utf-8") as fh:
        fh.write(json.dumps(words, ensure_ascii=False, indent=1))

    by_level = {}
    for w in words:
        by_level[w["level"]] = by_level.get(w["level"], 0) + 1
    print("Per-file kept:", stats)
    print("By level:", by_level)
    print(f"Dropped (dupes/invalid): {dropped}")
    print(f"TOTAL unique entries: {len(words)}")


if __name__ == "__main__":
    main()
